// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTask struct {
	ID string `json:"_id"`
}

type NewTask struct {
	Subject string `json:"subject"`
	Done    bool   `json:"done"`
}

type Task struct {
	ID      string `json:"_id"`
	Subject string `json:"subject"`
	Done    bool   `json:"done"`
}

type UpdateTask struct {
	ID      string `json:"_id"`
	Subject string `json:"subject"`
	Done    bool   `json:"done"`
}
